### ISSUE TITLE
Z-Wave Wakeup missing (COMMAND_CLASS_WAKE_UP)

### ISSUE THREAD

**Issue by daneedk** [athombv/com.aeotec#10]
I am missing the COMMAND_CLASS_WAKE_UP in the settings for the MultiSensor 6 as we had before the z-wave rewrite (See the screenshot, Z-Wave Wakeup field, configurable in seconds).

I guess it may be something that should not be made available in this app but on a z-wave generic level, if this is the case, please point me to the place where to raise this issue.

The reason I ask for having this setting available is because it enables a usefull Selective Reporting on a battery powered device (for example MultiSensor 6). Selective Reporting will send a report when a change in a sensor reading is larger then the configured threshold (parameters 41-45 when 40 is enabled). 
These sensor readings take place when the device is woken up, on USB power this is every 10 seconds but on battery power this needs to be configured through the COMMAND_CLASS_WAKE_UP.

![settingstempcorr](https://cloud.githubusercontent.com/assets/16610696/18505245/a065776e-7a66-11e6-9554-b02ed7881975.png)

**Comment by WeeJeWel** [comment]
Thanks for reporting! This is in the road map to support globally instead of on app level.

**Comment by daneedk** [comment]
Thank you!
