### ISSUE TITLE
Support for DSA03202 (minimote)

### ISSUE THREAD

**Issue by gn0st1c** [athombv/com.aeotec#101]
please add support for; https://products.z-wavealliance.org/products/143

**Comment by RobinBol** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
