### ISSUE TITLE
Recessed Door Sensor pairing fails

### ISSUE THREAD

**Issue by ks2018ks** [athombv/com.aeotec#105]
Hi I've tried paring over and over with 7 Recessed Door Sensors.  Only the first paired. The others fail at various points.  Tried various distances 50cm -> 2cm away from homey.

This is usual pattern:

VM3250:1 status ADD_NODE_STATUS_LEARN_READY
VM3250:1 status ADD_NODE_STATUS_NODE_FOUND
VM3250:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3250:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3250:1 status ADD_NODE_STATUS_DONE
VM3250:1 status INTERVIEW_SECURITY
VM3250:1 status INTERVIEW_CC
VM3335:1 status WAIT
VM3335:1 status ADD_NODE_STATUS_LEARN_READY
VM3335:1 status ADD_NODE_STATUS_NODE_FOUND
VM3335:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3335:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3335:1 status ADD_NODE_STATUS_DONE
VM3335:1 status INTERVIEW_SECURITY
VM3335:1 status INTERVIEW_SECURITY_CC
VM3335:1 status INTERVIEW_CC
VM3420:1 status WAIT
VM3420:1 status ADD_NODE_STATUS_LEARN_READY
VM3420:1 status ADD_NODE_STATUS_NODE_FOUND
VM3420:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3420:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3420:1 status ADD_NODE_STATUS_DONE
VM3420:1 status INTERVIEW_SECURITY
VM3420:1 status INTERVIEW_SECURITY_CC
VM3420:1 status INTERVIEW_CC
VM3505:1 status WAIT
VM3505:1 status ADD_NODE_STATUS_LEARN_READY
VM3505:1 status ADD_NODE_STATUS_LEARN_READY
VM3505:1 status ADD_NODE_STATUS_NODE_FOUND
VM3505:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3505:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3505:1 status ADD_NODE_STATUS_DONE
VM3505:1 status INTERVIEW_SECURITY
VM3505:1 status INTERVIEW_SECURITY_CC
VM3505:1 status INTERVIEW_CC
VM3505:1 status INTERVIEW_CC_1_OF_17
VM3505:1 status INTERVIEW_CC_2_OF_17
VM3642:1 status WAIT
VM3642:1 status ADD_NODE_STATUS_LEARN_READY
VM3642:1 status ADD_NODE_STATUS_NODE_FOUND
VM3642:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3642:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3642:1 status ADD_NODE_STATUS_DONE
VM3642:1 status INTERVIEW_SECURITY
VM3642:1 status INTERVIEW_SECURITY_CC
VM3642:1 status INTERVIEW_CC
VM3642:1 status INTERVIEW_CC_1_OF_17
VM3727:1 status WAIT
VM3727:1 status ADD_NODE_STATUS_LEARN_READY
VM3727:1 status ADD_NODE_STATUS_NODE_FOUND
VM3727:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3727:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3727:1 status ADD_NODE_STATUS_DONE
VM3727:1 status INTERVIEW_SECURITY
VM3727:1 status INTERVIEW_CC
VM3812:1 status WAIT
VM3812:1 status ADD_NODE_STATUS_LEARN_READY
VM3812:1 status ADD_NODE_STATUS_NODE_FOUND
VM3812:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3812:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3812:1 status ADD_NODE_STATUS_DONE
VM3812:1 status INTERVIEW_SECURITY
VM3812:1 status INTERVIEW_CC
VM3897:1 status WAIT
VM3897:1 status ADD_NODE_STATUS_LEARN_READY
VM3897:1 status ADD_NODE_STATUS_NODE_FOUND
VM3897:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3897:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3897:1 status ADD_NODE_STATUS_DONE
VM3897:1 status INTERVIEW_SECURITY
VM3897:1 status INTERVIEW_SECURITY_CC
VM3897:1 status INTERVIEW_CC
VM3982:1 status WAIT
VM3982:1 status ADD_NODE_STATUS_LEARN_READY
VM3982:1 status ADD_NODE_STATUS_NODE_FOUND
VM3982:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM3982:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM3982:1 status ADD_NODE_STATUS_DONE
VM3982:1 status INTERVIEW_SECURITY
VM3982:1 status INTERVIEW_SECURITY_CC
VM3982:1 status INTERVIEW_CC
VM4067:1 status WAIT
VM4067:1 status ADD_NODE_STATUS_LEARN_READY
VM4067:1 status ADD_NODE_STATUS_NODE_FOUND
VM4067:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4067:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4067:1 status ADD_NODE_STATUS_DONE
VM4152:1 status WAIT
VM4152:1 status ADD_NODE_STATUS_LEARN_READY
VM4152:1 status ADD_NODE_STATUS_NODE_FOUND
VM4152:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4152:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4152:1 status ADD_NODE_STATUS_DONE
VM4237:1 status WAIT
VM4237:1 status ADD_NODE_STATUS_LEARN_READY
VM4237:1 status ADD_NODE_STATUS_NODE_FOUND
VM4237:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4237:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4237:1 status ADD_NODE_STATUS_DONE
VM4237:1 status INTERVIEW_SECURITY
VM4237:1 status INTERVIEW_SECURITY_CC
VM4237:1 status INTERVIEW_CC
VM4237:1 status INTERVIEW_CC_1_OF_17
VM4474:1 status WAIT
VM4474:1 status ADD_NODE_STATUS_LEARN_READY
VM4474:1 status ADD_NODE_STATUS_NODE_FOUND
VM4474:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4474:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4474:1 status ADD_NODE_STATUS_DONE
VM4474:1 status INTERVIEW_SECURITY
VM4474:1 status INTERVIEW_SECURITY_CC
VM4474:1 status INTERVIEW_CC
VM4474:1 status INTERVIEW_CC_1_OF_17
VM4474:1 status INTERVIEW_CC_2_OF_17
VM4474:1 status INTERVIEW_CC_3_OF_17
VM4474:1 status INTERVIEW_CC_4_OF_17
VM4559:1 status WAIT
VM4559:1 status ADD_NODE_STATUS_LEARN_READY
VM4559:1 status ADD_NODE_STATUS_NODE_FOUND
VM4559:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4559:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4559:1 status ADD_NODE_STATUS_DONE
VM4559:1 status INTERVIEW_SECURITY
VM4559:1 status INTERVIEW_SECURITY_CC
VM4559:1 status INTERVIEW_CC
VM4559:1 status INTERVIEW_CC_1_OF_17
VM4644:1 status WAIT
VM4644:1 status ADD_NODE_STATUS_LEARN_READY
VM4644:1 status ADD_NODE_STATUS_NODE_FOUND
VM4644:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4644:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4644:1 status ADD_NODE_STATUS_DONE
VM4644:1 status INTERVIEW_SECURITY
VM4644:1 status INTERVIEW_CC
VM4729:1 status WAIT
VM4729:1 status ADD_NODE_STATUS_LEARN_READY
VM4729:1 status ADD_NODE_STATUS_NODE_FOUND
VM4729:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4729:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4729:1 status ADD_NODE_STATUS_DONE
VM4729:1 status INTERVIEW_SECURITY
VM4729:1 status INTERVIEW_CC
VM4814:1 status WAIT
VM4814:1 status ADD_NODE_STATUS_LEARN_READY
VM4814:1 status ADD_NODE_STATUS_LEARN_READY
VM4814:1 status ADD_NODE_STATUS_NODE_FOUND
VM4814:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4814:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4814:1 status ADD_NODE_STATUS_DONE
VM4814:1 status INTERVIEW_SECURITY
VM4814:1 status INTERVIEW_CC
VM4899:1 status WAIT
VM4899:1 status ADD_NODE_STATUS_LEARN_READY
VM4899:1 status ADD_NODE_STATUS_NODE_FOUND
VM4899:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4899:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4899:1 status ADD_NODE_STATUS_DONE
VM4899:1 status INTERVIEW_SECURITY
VM4899:1 status INTERVIEW_CC
VM4984:1 status WAIT
VM4984:1 status ADD_NODE_STATUS_LEARN_READY
VM4984:1 status ADD_NODE_STATUS_LEARN_READY
VM4984:1 status ADD_NODE_STATUS_NODE_FOUND
VM4984:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM4984:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM4984:1 status ADD_NODE_STATUS_DONE
VM4984:1 status INTERVIEW_SECURITY
VM4984:1 status INTERVIEW_CC
VM5069:1 status WAIT
VM5069:1 status ADD_NODE_STATUS_LEARN_READY
VM5069:1 status ADD_NODE_STATUS_DONE
VM5154:1 status WAIT
VM5154:1 status ADD_NODE_STATUS_LEARN_READY
VM5154:1 status ADD_NODE_STATUS_NODE_FOUND
VM5154:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5154:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5154:1 status ADD_NODE_STATUS_DONE
VM5154:1 status INTERVIEW_SECURITY
VM5154:1 status INTERVIEW_SECURITY_CC
VM5154:1 status INTERVIEW_CC
VM5239:1 status WAIT
VM5239:1 status ADD_NODE_STATUS_LEARN_READY
VM5239:1 status ADD_NODE_STATUS_NODE_FOUND
VM5239:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5239:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5239:1 status ADD_NODE_STATUS_DONE
VM5239:1 status INTERVIEW_SECURITY
VM5239:1 status INTERVIEW_CC
VM5324:1 status WAIT
VM5324:1 status ADD_NODE_STATUS_LEARN_READY
VM5324:1 status ADD_NODE_STATUS_NODE_FOUND
VM5324:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5324:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5324:1 status ADD_NODE_STATUS_DONE
VM5324:1 status INTERVIEW_SECURITY
VM5324:1 status INTERVIEW_CC
VM5468:1 status WAIT
VM5468:1 status ADD_NODE_STATUS_LEARN_READY
VM5468:1 status ADD_NODE_STATUS_NODE_FOUND
VM5468:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5468:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5468:1 status ADD_NODE_STATUS_DONE
VM5468:1 status INTERVIEW_SECURITY
VM5468:1 status INTERVIEW_CC
VM5553:1 status WAIT
VM5553:1 status ADD_NODE_STATUS_LEARN_READY
VM5553:1 status ADD_NODE_STATUS_NODE_FOUND
VM5553:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5553:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5553:1 status ADD_NODE_STATUS_DONE
VM5553:1 status INTERVIEW_SECURITY
VM5553:1 status INTERVIEW_CC
VM5638:1 status WAIT
VM5638:1 status ADD_NODE_STATUS_LEARN_READY
VM5638:1 status ADD_NODE_STATUS_LEARN_READY
VM5638:1 status ADD_NODE_STATUS_NODE_FOUND
VM5638:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5638:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5638:1 status ADD_NODE_STATUS_DONE
VM5638:1 status INTERVIEW_SECURITY
VM5638:1 status INTERVIEW_CC
VM5723:1 status WAIT
VM5723:1 status ADD_NODE_STATUS_LEARN_READY
VM5723:1 status ADD_NODE_STATUS_LEARN_READY
VM5723:1 status ADD_NODE_STATUS_NODE_FOUND
VM5723:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5723:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5723:1 status ADD_NODE_STATUS_DONE
VM5723:1 status INTERVIEW_SECURITY
VM5723:1 status INTERVIEW_CC
VM5808:1 status WAIT
VM5808:1 status ADD_NODE_STATUS_LEARN_READY
VM5808:1 status ADD_NODE_STATUS_NODE_FOUND
VM5808:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5808:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5808:1 status ADD_NODE_STATUS_DONE
VM5808:1 status INTERVIEW_SECURITY
VM5808:1 status INTERVIEW_CC
VM5893:1 status WAIT
VM5893:1 status ADD_NODE_STATUS_LEARN_READY
VM5893:1 status ADD_NODE_STATUS_LEARN_READY
VM5893:1 status ADD_NODE_STATUS_NODE_FOUND
VM5893:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM5893:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM5893:1 status ADD_NODE_STATUS_DONE
VM5893:1 status INTERVIEW_SECURITY
VM5893:1 status INTERVIEW_CC

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker

**Comment by ks2018ks** [comment]
Hi, thanks for your response.  So as to help me help you help me, could you give me an idea about what is missing in the above, so that I can post better another issue?

Looking at the guidelines you referenced it says, I should provide
_Context – what were you trying to achieve?_
that not covered in the term 'paring'

_Detailed steps to reproduce the error from scratch. Try isolating the minimal amount of code needed to reproduce the error._

Try to pair Aeotec Recessed Door Sensors. Only the first paired. The others fail at various points. Tried various distances 50cm -> 2cm away from Homey.

_Any applicable log files or ID's._
I don't know what's in a Homey log file, so I don't really know what's applicable, but previously I have sent a log with code: B34FDF232E

_Evidence you've looked into solving the problem and ideally, a theory on the cause and a possible solution._
I'm not sure what evidence I can produce of searching the forum, here and banging my head against the wall, but I have a video of the problem happening in real time here: [https://youtu.be/ZkL4ZWog3Gs](url)
Is that any good?

Please let me know if I am missing something, and so I can repost.  Thanks
