### ISSUE TITLE
Application Validation Issue

### ISSUE THREAD

**Issue by specialcircumstances** [athombv/com.aeotec#109]
When trying to validate the app I get the following, even on a shiny new clone of the repo.

athom --version
2.1.21

npm --version
5.6.0

node --version
v8.10.0

`
...Code\Athom\test\com.aeotec>athom app validate
...

Homey App did not validate against level `debug`:
[
    {
        "keyword": "enum",
        "dataPath": ".drivers[1].settings[0].type",
        "schemaPath": "#/items/oneOf/0/properties/type/enum",
        "params": {
            "allowedValues": [
                "text",
                "password",
                "textarea",
                "label"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "enum",
        "dataPath": ".drivers[1].settings[0].type",
        "schemaPath": "#/items/oneOf/1/properties/type/enum",
        "params": {
            "allowedValues": [
                "number",
                "slider"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "enum",
        "dataPath": ".drivers[1].settings[0].type",
        "schemaPath": "#/items/oneOf/2/properties/type/enum",
        "params": {
            "allowedValues": [
                "radio",
                "dropdown"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "type",
        "dataPath": ".drivers[1].settings[0].id",
        "schemaPath": "#/items/oneOf/3/properties/id/type",
        "params": {
            "type": "string"
        },
        "message": "should be string"
    },
    {
        "keyword": "enum",
        "dataPath": ".drivers[1].settings[0].type",
        "schemaPath": "#/items/oneOf/4/properties/type/enum",
        "params": {
            "allowedValues": [
                "group"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "oneOf",
        "dataPath": ".drivers[1].settings[0]",
        "schemaPath": "#/items/oneOf",
        "params": {
            "passingSchemas": null
        },
        "message": "should match exactly one schema in oneOf"
    }
]
`

**Comment by RobinBol** [comment]
That is caused (mostly) by the settings having a number as id which is no longer allowed with the updated validator.

**Comment by specialcircumstances** [comment]
OK. Understood. Have corrected them all e.g. "id"=123 is now "id"="123" across the board. This resolved the validation issues. I will include in next pull request, which I'll hold off until #53 is resolved.
