### ISSUE TITLE
Support for ZW140

### ISSUE THREAD

**Issue by deepvalleySE** [athombv/com.aeotec#113]
Any chance for an update that adds support for the Dual Nano Switch ZW140?

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location.This issue will be closed now, our apologies for the inconvenience.
