### ISSUE TITLE
Wrong Name for HEM ZW095C?

### ISSUE THREAD

**Issue by lesterchan** [athombv/com.aeotec#114]
It seems the model ZW095C is indicated as "Home Energy Meter Gen2" in https://github.com/athombv/com.aeotec/blob/master/config/drivers/ZW095C.json

Whereas if you google for ZW095, it is the name for Home Energy Meter Gen5.

I am using  Home Energy Meter (2nd Edition) and I assumed that is Gen2 and the model number is DSB28.

So I am confused as to whether it is supporting ZW095 or DSB28.

cc @specialcircumstances

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.

**Comment by specialcircumstances** [comment]
PS That was sorted out in the last pull request I made... 

https://github.com/athombv/com.aeotec/pull/110

**Comment by lesterchan** [comment]
@specialcircumstances awesome. Can't wait for it to be merged.
