### ISSUE TITLE
Recessed Door Sensor, not able to delete

### ISSUE THREAD

**Issue by ParkerJulius** [athombv/com.aeotec#121]
Hi,
I have a device that im not able to remove, i tried adding it again and that works fine, so now i have to devices from the same, but onlu one of them are working. 

I tried to remove it but I only get this message: vdevice.drivers.zwavebasic.pair.response_timeout

Im running Homey Firmware Version: 1.5.11 and Aeotec v1.6.4

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
