### ISSUE TITLE
Cannot include the Aeotec Garage Door Opener

### ISSUE THREAD

**Issue by skarotech** [athombv/com.aeotec#127]
Hi, I am in Australia, with an australian frequency Homey and Aeotec Garage Door Opener.

I cannot get the opener to include, I have tried around 30 times last night, and no luck.

It just gets stuck at one of the following and never finishes the setup properly.

- Fails setting up security key.
- gets stuck in the command class association (eg 3/18 or 16/18)
- once it got past the associations and came back as unknown device

I have the two units side by side , so its not a distance issue, it just won't include.

**Comment by jeroenvollenbrock** [comment]
Hi Skarotech,

We're sorry to hear your Homey is not functioning as expected. Please note that this however is a bug tracker and not a regular support channel. The fastest way to get direct support is by sending an e-mail to support@athom.com. Could you contact them and include some information about the non-functioning product? For instance, are other Z-Wave products working without issues? What is the product code of the garage door opener? How many devices are already included in your Z-Wave network? The more information we have, the easier it is to help you to resolve this.

**Comment by daneedk** [comment]
Isn't this just the missing Product Type ID for the AUS version of the device?

Change:

https://github.com/athombv/com.aeotec/blob/652c7f28cedd2e07893487da022f8be778e5b21d/app.json#L486

to: 

"productTypeId": [ 3, 515 ],

(There's a forum topic with more information about this: 
https://community.athom.com/t/cannot-include-aeotec-garage-door-opener/648)

**Comment by jeroenvollenbrock** [comment]
It might be, but even if that's the case the pairing shouldn't fail to exchange security keys.

**Comment by MatthewWaanders** [comment]
This is fixed in version 1.6.7! It was indeed a problem with the Australian IDs being different from the European ones. Sadly there isn't a central database that lists all of these, so if you find any other missing IDs please let us know!
