### ISSUE TITLE
Dual nano swtich support?

### ISSUE THREAD

**Issue by kentaclub** [athombv/com.aeotec#128]
Hi,

You can wirte more for Dual Nano switch.
Identifier : ZW132-C
Details : https://products.z-wavealliance.org/products/2151

Thanks.

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
