### ISSUE TITLE
Support for Smart Energy Illuminator DSC08101 - ZWEU

### ISSUE THREAD

**Issue by zeppie** [athombv/com.aeotec#149]
Will there be support for this device? Hopefully yes. If not, are there any guidelines how I can help? TIA, Zeppie

**Comment by kentaclub** [comment]
Seems this product Aeotec has ceased production, and replaced it as Smart Switch 6.

If you want to pair Smart Energy illuminator, you can copy the driver ZW096 and replace Producttypeid, ProductID. I think it can work.

**Comment by zeppie** [comment]
thx, I will give it a go. keep u posted.

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
