### ISSUE TITLE
Smart Switch 6 not showing power usage

### ISSUE THREAD

**Issue by FreeFrags** [athombv/com.aeotec#33]
It seems like my switch isn't showing the power usage. In the insights tab only the Turned on logs are shown.

**Comment by busscher** [comment]
Please try to re-add the Smart Switch 6 again. 
it helped me

**Comment by RobinBol** [comment]
@FreeFrags have you tried re-adding it? Did it solve your problem?

**Comment by RobinBol** [comment]
I'll close this issue due to inactivity, if at a later point in time you still find yourself having this problem please let me know.
