### ISSUE TITLE
How to get Aeotec sirene Gen5 working with a flow or device ?

### ISSUE THREAD

**Issue by backslashgithub** [athombv/com.aeotec#34]
Hello, i installed the Aeotec sirene Gen5 and Homey app v1.2.4. How do i get it working with a flow or device? thx in advance

**Comment by RobinBol** [comment]
So, I went ahead and added the flow cards, but could not test it yet. I have created a branch with the changes, I you'd like you can download the app from https://github.com/athombv/com.aeotec/tree/ZW080-onoff-flow-cards and side load it on your Homey to test the flow cards, just let me know if they work then I'll release them with an update of the Aeotec app.

**Comment by RobinBol** [comment]
@backslashgithub got any change to test the changes I made for you?:)

**Comment by backslashgithub** [comment]
no, not any changes.

**Comment by RobinBol** [comment]
Ehm, you need to checkout the ZW080-onoff-flow-cards branch, but I assume from your other comment that you are a bit new to this. You need to go to the link I posted above, and clone that onto your computer. Then you need to run the app as I pointed out in https://github.com/athombv/com.fibaro/issues/81#issuecomment-272891479

**Comment by Tweaqer** [comment]
+1 for this problem, any updates since we last spoke @RobinBol ?

**Comment by RobinBol** [comment]
Updated the Aeotec app with flow and mobile functionality for the Siren Gen5.

**Comment by backslashgithub** [comment]
@RobinBol  thanks for your work!

**Comment by Tweaqer** [comment]
@RobinBol geweldig!
