### ISSUE TITLE
No power reading on AEO_ZW075

### ISSUE THREAD

**Issue by djeskoswe** [athombv/com.aeotec#36]
No power reading on AEO_ZW075,  just a - in card.

http://products.z-wavealliance.org/products/1045

**Comment by RobinBol** [comment]
Are you able to run the app in debug mode by side loading it on you Homey and setting the debug flag to true in zwave-driver?

```
module.exports = new ZwaveDriver(path.basename(__dirname), {
	debug: true,
	capabilities: {
	}
});
```

If so I might be able to find your issue from the logging.

**Comment by djeskoswe** [comment]
Will do this tomorrow,  been sick!

**Comment by djeskoswe** [comment]
@RobinBol 

where do i change the debug ?  new to me ..

**Comment by Sillec123** [comment]
I have the same problem! How can i side load the app?

**Comment by Sillec123** [comment]
4/4 - Debugging...

-------------------------------------------------
com.aeotec running...
[debug] get onoff
[debug] ------------------------------------------
[debug] Node: 39f73627-bcb1-4453-a063-d251d8b30dab
[debug] - Battery: false
[debug] - CommandClass: COMMAND_CLASS_SWITCH_BINARY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- SWITCH_BINARY_GET
[debug] --- SWITCH_BINARY_REPORT
[debug] --- SWITCH_BINARY_SET
[debug] - CommandClass: COMMAND_CLASS_METER
[debug] -- Version: 3
[debug] -- Commands:
[debug] --- METER_GET
[debug] --- METER_REPORT
[debug] --- METER_RESET
[debug] --- METER_SUPPORTED_GET
[debug] --- METER_SUPPORTED_REPORT
[debug] - CommandClass: COMMAND_CLASS_SWITCH_ALL
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- SWITCH_ALL_GET
[debug] --- SWITCH_ALL_OFF
[debug] --- SWITCH_ALL_ON
[debug] --- SWITCH_ALL_REPORT
[debug] --- SWITCH_ALL_SET
[debug] - CommandClass: COMMAND_CLASS_SCENE_ACTUATOR_CONF
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- SCENE_ACTUATOR_CONF_GET
[debug] --- SCENE_ACTUATOR_CONF_REPORT
[debug] --- SCENE_ACTUATOR_CONF_SET
[debug] - CommandClass: COMMAND_CLASS_SCENE_ACTIVATION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- SCENE_ACTIVATION_SET
[debug] - CommandClass: COMMAND_CLASS_CONFIGURATION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- CONFIGURATION_GET
[debug] --- CONFIGURATION_REPORT
[debug] --- CONFIGURATION_SET
[debug] - CommandClass: COMMAND_CLASS_ASSOCIATION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- ASSOCIATION_GET
[debug] --- ASSOCIATION_GROUPINGS_GET
[debug] --- ASSOCIATION_GROUPINGS_REPORT
[debug] --- ASSOCIATION_REMOVE
[debug] --- ASSOCIATION_REPORT
[debug] --- ASSOCIATION_SET
[debug] - CommandClass: COMMAND_CLASS_CRC_16_ENCAP
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- CRC_16_ENCAP
[debug] - CommandClass: COMMAND_CLASS_MANUFACTURER_SPECIFIC
[debug] -- Version: 2
[debug] -- Commands:
[debug] --- MANUFACTURER_SPECIFIC_GET
[debug] --- MANUFACTURER_SPECIFIC_REPORT
[debug] --- DEVICE_SPECIFIC_GET
[debug] --- DEVICE_SPECIFIC_REPORT
[debug] - CommandClass: COMMAND_CLASS_VERSION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- VERSION_COMMAND_CLASS_GET
[debug] --- VERSION_COMMAND_CLASS_REPORT
[debug] --- VERSION_GET
[debug] --- VERSION_REPORT
[debug] - CommandClass: COMMAND_CLASS_BASIC
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- BASIC_GET
[debug] --- BASIC_REPORT
[debug] --- BASIC_SET
[debug] - CommandClass: COMMAND_CLASS_HAIL
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- HAIL
[debug] ------------------------------------------

[debug]  COMMAND_CLASS_METER->METER_GET args: { 'Sensor Type': 'Electric meter', Properties1: { Scale: 0 } } cb: true
[debug]  COMMAND_CLASS_METER->METER_GET args: { 'Sensor Type': 'Electric meter', Properties1: { Scale: 2 } } cb: true
[debug]  COMMAND_CLASS_METER METER_GET args: { 'Sensor Type': 'Electric meter', Properties1: { Scale: 0 } } err: null result: { 'Properties1 (Raw)': <Buffer 21>,
  Properties1: 
   { 'Meter Type': 1,
     'Rate Type': 1,
     'Scale bit 2': false,
     'Meter Type (Parsed)': { value: 1, name: 'Single-E electric meter' },
     'Rate Type (Parsed)': { value: 1, name: 'Import' } },
  'Properties2 (Raw)': <Buffer 64>,
  Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
  'Meter Value': <Buffer 00 00 00 00>,
  'Delta Time (Raw)': <Buffer 00 00>,
  'Delta Time': 0,
  'Previous Meter Value': <Buffer 00 00 00 00>,
  'Meter Value (Parsed)': 0,
  'Previous Meter Value (Parsed)': 0 }
[debug] get onoff
[debug]  COMMAND_CLASS_METER METER_GET args: { 'Sensor Type': 'Electric meter', Properties1: { Scale: 2 } } err: null result: { 'Properties1 (Raw)': <Buffer 21>,
  Properties1: 
   { 'Meter Type': 1,
     'Rate Type': 1,
     'Scale bit 2': false,
     'Meter Type (Parsed)': { value: 1, name: 'Single-E electric meter' },
     'Rate Type (Parsed)': { value: 1, name: 'Import' } },
  'Properties2 (Raw)': <Buffer 74>,
  Properties2: { Size: 4, 'Scale bits 10': 2, Precision: 3 },
  'Meter Value': <Buffer 00 00 0c 68>,
  'Meter Value (Parsed)': 3.176 }
[debug] set onoff true
[debug]  COMMAND_CLASS_SWITCH_BINARY
					->SWITCH_BINARY_SET args: { 'Switch Value': true }
[debug] node.CommandClass['COMMAND_CLASS_SWITCH_BINARY'].on('report') arguments: { '0': { value: 1, name: 'SWITCH_BINARY_SET' },
  '1': 
   { 'Switch Value (Raw)': <Buffer ff>,
     'Switch Value': 'on/enable' },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 3, name: 'BASIC_REPORT' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] set onoff false
[debug]  COMMAND_CLASS_SWITCH_BINARY
					->SWITCH_BINARY_SET args: { 'Switch Value': false }
[debug] node.CommandClass['COMMAND_CLASS_SWITCH_BINARY'].on('report') arguments: { '0': { value: 1, name: 'SWITCH_BINARY_SET' },
  '1': 
   { 'Switch Value (Raw)': <Buffer 00>,
     'Switch Value': 'off/disable' },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 3, name: 'BASIC_REPORT' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[debug] set onoff true
[debug]  COMMAND_CLASS_SWITCH_BINARY
					->SWITCH_BINARY_SET args: { 'Switch Value': true }
[debug] node.CommandClass['COMMAND_CLASS_SWITCH_BINARY'].on('report') arguments: { '0': { value: 1, name: 'SWITCH_BINARY_SET' },
  '1': 
   { 'Switch Value (Raw)': <Buffer ff>,
     'Switch Value': 'on/enable' },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 3, name: 'BASIC_REPORT' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 17>,
     'Delta Time': 23,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 1e>,
     'Delta Time': 30,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 18>,
     'Delta Time': 24,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1': 
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1: 
      { 'Meter Type': 1,
        'Rate Type': 1,
        'Scale bit 2': false,
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 64>,
     Properties2: { Size: 4, 'Scale bits 10': 0, Precision: 3 },
     'Meter Value': <Buffer 00 00 00 00>,
     'Delta Time (Raw)': <Buffer 00 06>,
     'Delta Time': 6,
     'Previous Meter Value': <Buffer 00 00 00 00>,
     'Meter Value (Parsed)': 0,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }

**Comment by djeskoswe** [comment]
@Sillec123 

Thanks ,

**Comment by Sillec123** [comment]
@djeskoswe
I hope they will fix the issue.
