### ISSUE TITLE
Aeotec door / window sensor 6

### ISSUE THREAD

**Issue by Bozo29** [athombv/com.aeotec#38]
Can you support the door/window sensor 6 ?
I have one on the frontdoor.
It's in my opinion the most beautiful and practical door/window sensor.

**Comment by busscher** [comment]
Why isn't there any update or comments?

**Comment by AKoetsier** [comment]
I have implemented the ZW112 Door/Window Sensor 6 driver locally. Just missing the images needed for the interface (learnmode/large/small). Any ideas on how to get/create those?
