### ISSUE TITLE
Support for Aeotec Range Extender 6 - Z-Wave+ extender - ZW117-C15

### ISSUE THREAD

**Issue by Dennizz** [athombv/com.aeotec#40]
This is the recently released zwave+ extender from Aeotec. If reuired I have 2 extenders available for testing.

**Comment by RobinBol** [comment]
Could you pair the device as basic zwave and post a screenshot of the node information table in the device settings? Then I can easily add the device.

**Comment by Dennizz** [comment]
Hi Robin, hope this is what you are looking for:

![image](https://cloud.githubusercontent.com/assets/1299878/23330893/373e93ee-fb5b-11e6-830a-fdd77aae7644.png)

**Comment by RobinBol** [comment]
Yes, thank you!

**Comment by RobinBol** [comment]
I have created a driver for your device, I could not test it however as we do not have the device (yet). Would you be willing to test it for me?

Get the app and driver from this branch, and run it on your Homey (https://developers.athom.com/library/getting-started/):
https://github.com/athombv/com.aeotec/tree/range-extender-6

**Comment by Dennizz** [comment]
Thanks Robin, I checked out the branch and installed it. I can add the range extenders as Aeotec devices. I don't see any of my zwave devices using them as a relay node just yet in the topology view though. Will give it some time and see what happens. I can imagine the battery devices don't pick up on this so quickly as they only wake up every so often...

**Comment by RobinBol** [comment]
Ok thanks, the mesh network will correct itself over time to use the extender if necessary. If you have any other comments or improvements let me know, otherwise I will add the device to the Aeotec app in the app store.
