### ISSUE TITLE
Which time value for "Motion Alarm delay"?

### ISSUE THREAD

**Issue by WesRos** [athombv/com.aeotec#41]
In the settings overview for the MultiSensor 6 there is a time value. But I don't know seconds, hours, day?
Could this explain in this overview?

![image](https://cloud.githubusercontent.com/assets/8507396/23318857/75a85b88-fad4-11e6-934c-d7a050edb156.png)

App version 1.2.9

**Comment by RobinBol** [comment]
It is exactly the same as is specified in the manual of your device. In the next app update I'll add some more information in the hint, thanks.
