### ISSUE TITLE
Switching LED on/off Multisensor 6

### ISSUE THREAD

**Issue by Povlov** [athombv/com.aeotec#52]
In settings pane, add a box to turn movement indicator LED off.

![screenshot 2017-04-24 at 16 24 37](https://cloud.githubusercontent.com/assets/24312420/25342409/4b4badca-290c-11e7-93fa-b36232e6098b.png)

**Comment by caseda** [comment]
As also stated on Slack:
It can only be turned off in the latest Firmware (>=1.0.8) of the Multisensor 6
See the bottom of the page for the changelog for 1.0.8:
https://aeotec.freshdesk.com/support/solutions/articles/6000036562-multisensor-6-firmware-update-6-17-2016-new-information-v1-08-11-02-2016-

**Comment by RobinBol** [comment]
Will not add this setting as not all Multisensors support it, and there is no way of updating the firmware of these devices at the moment (via Homey). If you want to use the raw configuration parameters: 81, 1, 1.

**Comment by Povlov** [comment]
Thanks for looking into!
