### ISSUE TITLE
Support for Aeon Labs Micro Smart Energy Switch (Product ID 12)

### ISSUE THREAD

**Issue by blavla** [athombv/com.aeotec#58]
Hi,
I'm owning a couple Aeon Labs Micro Smart Energy Switch's, and it looks like they aren't supported yet. I think these are oldies :)

If I add them they are added as a Unknown Z-Wave Device. With that I can control the switch from Homey, but when I manually toggle the switch, the Homey isn't being notified/updated.

The Node Information:
Manufacturer ID: 134
Product Type ID: 3
Product ID: 12

I hope you can add these.

**Comment by RobinBol** [comment]
Duplicate of https://github.com/athombv/com.aeotec/issues/55
