### ISSUE TITLE
Support for FOXX rebranded Aeotec DSB29 Door Sensor (2nd Generation)

### ISSUE THREAD

**Issue by MbenzNo** [athombv/com.aeotec#61]
I Need an app for FOXX Door/Window sensor 2nd Gen. (Piper magnet door sensor) This seems to be a rebranded version of Aeotec DSB29 Door Sensor (2nd Generation)
Manual: http://manuals-backend.z-wave.info/make.php?lang=en&type=&sku=FOXEDWSENS

Node ID: 49
Secure: No
Battery: Yes
Manufacturer ID: 134
Product type ID: 2
Product ID: 29
Device Class (Basic): BASIC_TYPE_ROUTING_SLAVE
Device Class (Generic): GENERIC_TYPE_SENSOR_BINARY
Device Class (Specific): SPECIFIC_TYPE_ROUTING_SENSOR_BINARY

**Comment by RobinBol** [comment]
Sorry, we will not add rebranded devices to the Aeotec app. If you want, you can create a Z-Wave driver yourself or ask around the Athom forum to see if there are more people that want it!
