### ISSUE TITLE
When battery's are empty of the 4 in 1 sensor

### ISSUE THREAD

**Issue by basd82** [athombv/com.aeotec#62]
When battery's are empty of the 4 in 1 sensor.
And you ask homey what the temp is it answers

In the zip a wave file so you can here your self.
It sould report some kind of er but not this 
it's naan degrees

[Spraak 003_sd.zip](https://github.com/athombv/com.aeotec/files/1045795/Spraak.003_sd.zip)

**Comment by caseda** [comment]
just a side note, since the OP needed to leave, the value was empty ( - ) when it happend, so might be an homey issue with Null as value

**Comment by RobinBol** [comment]
Hi, thanks for reporting this issue, I have mentioned this issue here: https://github.com/athombv/homey/issues/1898 as it is related to that. I will close this issue for now.
