### ISSUE TITLE
Support for Nano Dimmer and Nano Switch

### ISSUE THREAD

**Issue by ljsvv** [athombv/com.aeotec#72]
Dear Atom team.

I am planning to buy the wall mote quad switch so that I can gradually phase out all my KAKU devices.

Can you please tell me when the Nano Dimmer and Nano Switch will be supported?

Thanks!

**Comment by mchieppa** [comment]
This is something I would like too. I have some programming skills. Is it only editting the app.json?

**Comment by mchieppa** [comment]
made the part for app.json and the ZW111 drivers folder
could someone check these files and take a look at parameter 85 and 86
these parameters contain 4 values and I don't know how to put it in the app.json
maybe someone could also check the driver.js
see attached files
[nanodimmerpart.zip](https://github.com/athombv/com.aeotec/files/1224526/nanodimmerpart.zip)

**Comment by friso** [comment]
@RobinBol Noticed you've pushed commit to a branch for this recently. Any timeline on merging (or release as a beta)? I have a nano dimmer device and am happy to test.

**Comment by RobinBol** [comment]
Just updated the Aeotec app with support for the Nano Dimmer/Switch, please let me know if you find any issues!

**Comment by mchieppa** [comment]
Thanks Robin, I'll test it later today or tomorrow.

**Comment by mchieppa** [comment]
Looks like it's working correct, thanks!
