### ISSUE TITLE
Support for Heavy Duty Switch ZW078

### ISSUE THREAD

**Issue by Allram** [athombv/com.aeotec#79]
Please add support for the Heavy Duty Switch from Aeotec. It's the only switch i have seen for Z-wave which has support for upto 40Amps.

ZW078

**Comment by RobinBol** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
