### ISSUE TITLE
Support for: Micro Dimmer G2 and Micro Smart Dimmer G2

### ISSUE THREAD

**Issue by twister5800** [athombv/com.aeotec#84]
Any plans on supporting:
Micro Dimmer G2 and Micro Smart Dimmer G2
have a lot of theese :-)

**Comment by silikone** [comment]
Second this request for the Micro Dimmers

**Comment by RobinBol** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
