### ISSUE TITLE
Support for Door / Window Sensor Gen5 ZW120

### ISSUE THREAD

**Issue by tboudri** [athombv/com.aeotec#87]
Can you please add support for the ZW120 Door/Window sensor?

**Comment by Patrikgolfer** [comment]
Is there a timeline when this product will be supported ?

**Comment by RobinBol** [comment]
See my comment here for the latest update: https://github.com/athombv/com.aeotec/pull/104

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2572
