### ISSUE TITLE
Aeotec app made my homey unable to z-wave. Zwave always reports : Wait until z-wave is ready

### ISSUE THREAD

**Issue by mruiter** [athombv/com.aeotec#9]
Installed the Aeotec app. Added the smart switch 6. Worked for 3 days and then the whole of homeys z-wave became unresponsive.
Switches in flows did not get triggerd anymore (any brand, so also the Fibaros , Popp, Neo etc)
Adding a z-wave device Always gives "Wait until z-wave is ready"

Pull the plug, multiple reboots, nothing worked. 
Removing the com.aeotec app and doing a reboot fixed the problem.

Log file send to athom with number 6A5667FA54

The logfile was send in its zwave is Always busy state with the Aeotec app installed

**Comment by WeeJeWel** [comment]
This is not a problem of Aeotec but Z-Wave doing 'something' that blocks any other Z-Wave process.

Under Settings > Z-Wave > Stuff for geeks you can find what it is.

**Comment by mruiter** [comment]
The only thing changed was the aeotec app then . Multiple tests with one multisensor .
No flows on the ms and also tested different ms. All exact same result.
But this had been solved in the .10.x range so i guess it was something in zwave that has been fixed.

**Comment by mruiter** [comment]
So it can be closed now
