### ISSUE TITLE
Temperature Threshold setting - Multisensor 6 - correct value?

### ISSUE THREAD

**Issue by cbho** [athombv/com.aeotec#90]
When looking in the manual for the [Multisensor 6](https://forum.athom.com/uploads/editor/mt/tb0rjbphffxh.pdf), parameter 41 "Threshold change in temperature to induce an automatic report" is described to "2. The value contains one decimal point. E.g. if the value is set to 20, the threshold value =2.0 ℃"

In settings in Homey it says "If this temperature threshold (in Celcius) is exceeded..." and can be set to a value from 1-10 degrees.

As far as I can see in the code, the value set by the user in settings, is also the value sent to the device, thus the user may belive the threshold is set to 1 degree, but in fact it is set to 0.1 degree - thereby creating a lot more traffic than expected...

If in fact the value set is 1-10 degrees with steps of 1 degree (the value entered by the Homey-user is multiplied by 10 before sent to the device), and the device is capable of more detailed reporting, I suggest this is made possible.
If the value is not multiplied by 10, I suggest the wording and the variable limits are changed according to the manual to enable correct settings.

**Comment by RobinBol** [comment]
Parameter 41 [is multiplied by 10](https://github.com/athombv/com.aeotec/blob/master/drivers/ZW100/driver.js#L157), and it is possible to enter a value such as 2.5 in the setting. Using the arrows will indeed change the value by -1/+1.

**Comment by cbho** [comment]
Tried setting values like 2.5 and yes, that's possible.
However...

The device is constantly powered and set to only send threshold dependent updates - and with theparameter 41 set to 1.
As I understand it, the expected behavior would be, that updates are only sent when the temperature has changed +/- 1 degree Celcius (?)
Looking in Insights this is not the case - reports are sent with 0.1 degrees intervals:
(For keeping the overview, the picture is combined by a couple of screenshots to show the labels from each reading at the same picture).

![multisensor](https://user-images.githubusercontent.com/29979509/34994416-b9f8f572-fad3-11e7-94e6-845ebb3aebd0.png)

**Comment by cbho** [comment]
Changed parameter 41 to 10,
Expectedly, as the temperature is rather stable around 23 degrees Celcius in my bathroom, this should result in almost no updates on temperature, when "threshold dependent" is selected, if I get it right (?)

Combined screenshot as above:
![multisensor-2](https://user-images.githubusercontent.com/29979509/35070798-d19b2464-fbde-11e7-8356-c27436c3fd21.png)

**Comment by RobinBol** [comment]
You can try to use the raw configuration parameters in the device settings to ensure the values you send to the device are correct. If the device then still shows an irregular reporting behavior it is a problem with the device itself.

**Comment by cbho** [comment]
Will try systematically with settings that should be equivalent in Homey vs. raw configuration (like 1 in Homey and 10 in raw config), 24 hours of each and with some different values to generate an overview.
This will obviously take some time - will return when I have a lot of data ;-)

**Comment by cbho** [comment]
Have been logging data with different settings ("Homey"-style and "raw") for more than a month now.
The behaviour described when making this issue has not been reblicable - and the cause of the behaviour will remain unknown :-)
