### ISSUE TITLE
MultiSensor Gen 5 ZW074-C - Motion won't cancel since 1.6.2 update

### ISSUE THREAD

**Issue by ArchiSpec** [athombv/com.aeotec#92]
Was anything changed that would affect this in the latest update? Have 3 of the Gen 5 Multi-sensors and since the 1.6.2 update, motion alarm won't cancel. Tried removing and re-adding all 3 - same result.

Working perfectly before 1.6.2 update

Thanks in advance.

**Comment by ArchiSpec** [comment]
Update:- Vitaly Vlasov's solution from the app page comments corrects this:-  write the Raw configuration parameters 5,1,2 even though his solution was for a different model. But why is this necessary after the 1.6.2 update - surely this is a bug which has crept in??

**Comment by danone1973** [comment]
@ArchiSpec I've got the same problem with my 3 zw074. I've found few days back the forum post but in my case even after writing parameter 5,1,2 the motion alarm still does not cancel. It does actually but only for  while. I need to both PTP and soft reset.

**Comment by ArchiSpec** [comment]
@danone1973 Yes I think you're right. The patch parameter seemed to work briefly, then motion alarm stayed on. Client's install doesn't seem to have developed the same problem but thats running "stable" firmware 1.5.3, not experimental 1.5.6-rc.8 as my home rig. Is there a conflict between Aetoec 1.6.2 update and experimental firmware @RobinBol ??

@danone1973 does PTP & soft reset permanently sort it for you, or only temporarily?

**Comment by danone1973** [comment]
@ArchiSpec unfortunately a PTP and soft reset fixes this only temporarily. 
I use those three sensors around the house to turn on/off the security lights. I woke up many times to find my house surrounded by light because either one or more of the ZW074 got stuck into alarm motion.

I cannot really say since when this started to happen, either rc7 or rc8. But I don't think that it is because Aeotec 1.6.2. I had the same issue in 1.6.1
Anyway in rc6 or lower those ZW074 were rock solid unlike the Fibaro Multisensors. Now there is no difference in between them. Basically I have no usable motion sensors.
Patiently waiting for all this z-wave thing to be sorted...

**Comment by RobinBol** [comment]
There was a bug in <1.5.6 which prevented the defaultConfiguration parameters from being set when pairing the device, this might have to do with the problems you describe.

**Comment by danone1973** [comment]
As I read above from @ArchiSpec and my comments, the devices were already paired.

**Comment by ArchiSpec** [comment]
@danone1973 Yes, already paired and working absolutely fine for last 4 months until Aeotec 1.6.2 update. Weird, battery level being reported, but nothing else (no temp, hum, lux) and motion stuck on (sensor is working properly - red light comes on with motion still). Client install also on 1.6.2 absolutely fine, however thats on stable homey 1.5.3 not 1.5.6-rc.8. Does that help @RobinBol ? No errors being reported, but not showing as a battery device in tools either.

**Comment by danone1973** [comment]
@ArchiSpec and @RobinBol In my case all the ZW074 are powered via the USB. They report correctly the temperature, humidity and lux. But most of the time the motion alarm either gets stuck or not reported at all. Most of the time I mean almost all the time.
The test I've done: with no z-wave devices triggered across the whole network, moving in front of a ZW074, the motion is registered by Homey on and off correctly. If I keep moving around in front of the sensor or worst, start triggering other z-wave devices, the ZW074s either get stuck in motion alarm or don't reported back any motion (and also this happens on Fibaro motion sensors). Later, having the network quite and moving again in front of a ZW074 which is stuck into motion alarm, it gets this sensor back on track.
With my little knowledge of how Homey works, I think that it cannot simply handle any medium to heavy traffic on z-wave and misses sensors reporting for example motion stop.
I wonder if the guys at Athom have actually a decent z-wave network with various brands of sensors and create lots of triggers for testing.

Out of this topic, lately even devices like Fibaro button, Fibaro Universal Sensor and more, started to have a massive delay in response (3-10sec). PTP, soft reset, no help. This happens ONLY when the z-wave is heavy, meaning lots of triggers of various sensors e.g. motion when family members walk around house and trigger them. They should stay still, don't they? :)
I deleted most of the apps, currently only 6 apps left. I deleted almost all my flows, less than 15 flows left. Same thing! Sadly I have no home automation left at the moment trying to figure out what creates this problem.

**Comment by ArchiSpec** [comment]
OK, about midday today (UK) sensor starting working again all by itself! No explanation. Doesn't seem to be connected to the Aeotec update 1.6.3.a three days ago..... nor any system update....... odd...... cannot explain! Do any updates / system tweaks ever come though "silently"? (Without showing up under activity???)

**Comment by Reemster** [comment]
Same problem here, all my Gen 5 Multi-sensors stays in motion... Any idea when this problem got fixed?

**Comment by danone1973** [comment]
@ArchiSpec no change here after 1.6.3.
Just try this. move several times in front of the ZW074 and in the same time maybe have someone else triggering some other z-wave sensors battery powered or not. Or both. Then check if all your ZW074 returned to the non-breached status.
It is that Homey misses sensors status change if the z-wave network is busy.
I am running experimental 1.5.6. rc8.

**Comment by danone1973** [comment]
1.5.6 RC11 made no difference. After 24 hours ZW074 still either get stuck into continuous motion or don't report it at all.
There are plenty of mains powered devices around the and in between them and Homey.
A last hope is the stable version of 1.5.6.

**Comment by danone1973** [comment]
Nope. 1.5.6 has resolved nothing here. Back to HC2 as of today.

**Comment by jeroenvollenbrock** [comment]
Closed to combine under athombv/homey#2267
