### ISSUE TITLE
Product IDs missing for AUS/NZ z-wave frequency.

### ISSUE THREAD

**Issue by danone1973** [athombv/com.aeotec#93]
Add Product ID for AUS/NZ Z-wave frequency for the following devices, as they come up as Basic Z-wave device after pairing.

Nano dimmer ZW111 - PRODUCT TYPE ID - 515
Door/Window Sensor 6 ZW112 - PRODUCT TYPE ID - 514
Nano single switch ZW116 - PRODUCT TYPE ID - 515
Range Extender 6 (z-wave plus) ZW117 - PRODUCT TYPE ID - 516
Wallmote Quad ZW130 - PRODUCT TYPE ID - 514

It will take you 10 sec to add them @RobinBol  thank you

**Comment by RobinBol** [comment]
Fixed in v1.6.4
