### ISSUE TITLE
Aeotec SmartSwitch Power not Shown/Updated

### ISSUE THREAD

**Issue by CyberSponk** [athombv/com.aeotec#96]
**Metadata**

* **Homey Version**: 1.5.6-RC8
* **Homey Log Code**: -
* **Smartphone Platform**: Android
* **Smartphone App Version**: 0.8.5.115 (Beta)

**If related to a Homey App:** Aeotec
* **Homey App Version**: 1.6.3
* **Homey App Log Code**: -
* **Affected Devices (preferably product codes)**: SmartSwitch, Manufacturer ID 143, ProductType 3, Product-Type-ID 75 

**What did you try to achieve?**
Creating a Flow with "The Power Changed" in When-Column.

**What did you expect as result?**
Flow will be executed if Power of Switch changed.

**What was the result?**
Nothing. Flow didn't executed while Power changed.

**Any other remarks**
Power-Change: Switch Device On or Off. The Power-Tag-Information (also Insights) of a Switch not changing if attached Device e.g. Tv is turned on or off with Tv-Remote.

**Comment by danone1973** [comment]
I second this.
All three ZW075 I have are stuck reporting a power consumption. No change if the attached device is turned on/off.
Two out of four ZW096 have the same problem as above. The other two report correctly every single power change.

Moreover, all the above affected devices are either very slow in responding ON/OFF commands from Homey or they totally fail to respond any ON/OFF commands.

Aeotec app 1.6.3
Homey 1.5.6 RC8
Homey log: 4D735051FF

Have tried removing/including the device.
Have tried power cycle Homey and software reset.

**Comment by danone1973** [comment]
Meanwhile, I have reverted the Aeotec app to version 1.6.1 It made no difference.
Thought I would let you guys know.

**Comment by CyberSponk** [comment]
Updated Homey to 1.5.6-RC11 > No Difference.

**Comment by danone1973** [comment]
Same here no difference on 1.5.6 RC11.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.6-RC13.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.8-EXP from 08.03.18.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.11-EXP.

**Comment by tranceblast** [comment]
Updated Homey yesterday to 1.5.11. Still not working....

**Comment by tranceblast** [comment]
I now noticed that the first device I added is working fine, not the other 6 devices. If I remove all of them from Homey and add them in a other order, the first one is working and not the other. Perhaps the app has a bug that do that the app only can handle 1 device?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2570
