### ISSUE TITLE
More AUZ Devices pleace

### ISSUE THREAD

**Issue by tiimbo82** [athombv/com.aeotec#99]
Can i please have the following added:
Aeotec LED Globe ZW-098 product type id: 515, product id: 98
Aeotec Micro Smart Dimmer (2nd Edition) product type id: 3 product id: 19
Aeotec Micro Smart Switch (2nd Edition) product type id: 3 product id: 18
Aeotec (Aeon Labs Smart energy Illumiator) product type id 3 product id: 6
Aeotec (Aeon Labs Smart energy Illumiator)  Dimmable Lamp module product type 3 product id 8
Aeotec MICRO Double energy Switch product type 3 id 35

**Comment by tiimbo82** [comment]
Hey, any update on this, its holding me back from using homey as only 30% of devices work..

**Comment by RobinBol** [comment]
@MatthewWaanders could you add these device ids to the SDKv2 rewrite? Since the stable app can not be updated currently without some (duplicate) work.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2569
